services:
  PSQL:
    image: postgres:15-alpine3.19
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=brobroli
    ports:
      - 127.0.0.1:5432:5432
    volume:
      -postgres-data:/var/lib/postgres/data